# This is a basic workflow that is manually triggered

name: Manual test trigger workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment_name:
        description: 'Environment_name: The environmen to test the application'
        default: "dev"
        required: true
        type: choice
        options:
        - dev
        - stage
        - prod
      
      CUSTOMER_NUMBER:
        description: "CUSTOMER_NUMBER: Enter the customer Number"
        required: false
        default: "uhg"
        type: number
     
      TEST_FILE:
        description: 'TEST_FILE: Select test file to run'
        default: ""
        required: true
        type: choice
        options:
        - test_file_1.py
        - test_file_2.py
        - test_file_3.py
  
      MGID_COUNT:
        description: "MGID_COUNT: Number of member group IDs to generate"
        required: true
        default: ""
        type: number
   
      EFFECTIVE_DATE:
        description: "EFFECTIVE_DATE: MM/DD/YYYY format"
        required: true
        default: ""
        type: string
  
      ON_DEMAND_MIGRATION:
        description: "ON_DEMAND_MIGRATION: Enable on-demand Migration"
        required: false
        type: boolean

      OBM_PUBLISH:
        description: "OBM_PUBLISH: Enable OBM Publish"
        required: false
        type: boolean
   
      notifyDL:
        description: "notifyDL: Email results"
        required: false
        type: boolean
     
      TRIGGER_CIRRUS_JOB:
        description: "TRIGGER_CIRRUS_JOB: Trigger Cirrus Vikings QA job"
        required: false
        type: boolean
   
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Run test on Env
       run: echo "Run test script on ${{ github.event.inputs.environment_name }} environment"
