# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment_name:
        description: 'The environmen to test the application'
        default: "dev"
        required: true
        type: choice
        options:
        - dev
        - prod
        
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Run test on Env
       run: echo "Run test script on ${{ github.event.inputs.environment_name }}"
