# This is a basic workflow that is manually triggered

name: Manual test trigger workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment_name:
        description: 'The environmen to test the application'
        default: "dev"
        required: true
        type: choice
        options:
        - dev
        - stage
        - prod

      custom_message:
        description: "Enter the customer Name"
        required: false
        default: "uhg"
        type: string

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
     - name: Run test on Env
       run: echo "Run test script on ${{ github.event.inputs.environment_name }}"
